debug: false
# Triggered when you use /rtp without any additional paramters
# Just write your command as you would use it ingame here
# Don't use the -p parameter, this will get added automaticly with the senders name/the specified playername
presets:
   default: "/rtp 100 1000 -f"
# add more to use /rtp <rtpname>, player needs "randomteleport.presets.<rtpname>"
#   <rtpname>: "/rtp 1 2"
   test: "rtp 10 200 -f"

msg:
   search: "&7RandomTeleport searches for a safe place in world {worldname}. . ."
   teleport: "&7RandomTeleport teleported you to X: {x} Y: {y} Z: {z}!"
   setspawnpoint: "&7Your Respawnpoint has been set to your current location!"
   error:
      location: "&4Error: &cRandomTeleport could not find a save location!"
      cooldown: "&cYou have to wait {cooldown_text}before using this RandomTeleport again!"